#!/usr/bin/env python3
import argparse
import csv
import math
from pathlib import Path

import matplotlib.pyplot as plt


MOTOR_NAMES = [
    "FR_hip", "FR_thigh", "FR_calf",
    "FL_hip", "FL_thigh", "FL_calf",
    "RR_hip", "RR_thigh", "RR_calf",
    "RL_hip", "RL_thigh", "RL_calf",
]


def load_csv(path):
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise RuntimeError(f"No data rows in {path}")
    rows = [row for row in rows if float(row.get("has_state", "1")) > 0.5]
    if not rows:
        raise RuntimeError(
            "CSV contains no LowState feedback: has_state is 0 for every row. "
            "Start the Go2 simulator first, then rerun track_lowcmd_lowstate_go2."
        )

    data = {key: [] for key in rows[0].keys()}
    for row in rows:
        for key, value in row.items():
            data[key].append(float(value))
    return data


def parse_joints(value):
    if value == "all":
        return list(range(len(MOTOR_NAMES)))
    joints = []
    for item in value.split(","):
        item = item.strip()
        if not item:
            continue
        if item.isdigit():
            joints.append(int(item))
        else:
            joints.append(MOTOR_NAMES.index(item))
    return joints


def nice_grid(count):
    cols = 3 if count <= 6 else 4
    rows = math.ceil(count / cols)
    return rows, cols


def leg_grid_axes(joints):
    if joints == list(range(len(MOTOR_NAMES))):
        return 3, 4, [
            [0, 3, 6, 9],
            [1, 4, 7, 10],
            [2, 5, 8, 11],
        ]
    rows, cols = nice_grid(len(joints))
    grid = []
    for r in range(rows):
        grid.append(joints[r * cols:(r + 1) * cols])
    return rows, cols, grid


def plot_tracking(data, joints, out_path):
    t = data["cmd_time_s"]
    rows, cols, grid = leg_grid_axes(joints)
    fig, axes = plt.subplots(rows, cols, figsize=(4.4 * cols, 2.8 * rows), sharex=True)
    axes_grid = axes if rows > 1 else [axes]

    for r, row in enumerate(grid):
        for c in range(cols):
            ax = axes_grid[r][c] if rows > 1 else axes_grid[c]
            if c >= len(row):
                ax.axis("off")
                continue
            joint_idx = row[c]
            name = MOTOR_NAMES[joint_idx]
            q_target = data[f"{name}_q_target"]
            q_state = data[f"{name}_q_state"]
            ax.plot(t, q_target, label="target", linewidth=1.6)
            ax.plot(t, q_state, label="state", linewidth=1.1)
            ax.set_title(f"{joint_idx}: {name}")
            ax.set_ylabel("q [rad]")
            ax.grid(True, alpha=0.25)

    first_ax = axes_grid[0][0] if rows > 1 else axes_grid[0]
    first_ax.legend(loc="best")
    bottom_axes = axes_grid[-1] if rows > 1 else axes_grid
    for ax in bottom_axes:
        ax.set_xlabel("time [s]")
    fig.suptitle("Go2 LowCmd target vs LowState feedback")
    fig.tight_layout()
    fig.savefig(out_path, dpi=160)


def plot_error(data, joints, out_path):
    t = data["cmd_time_s"]
    rows, cols, grid = leg_grid_axes(joints)
    fig, axes = plt.subplots(rows, cols, figsize=(4.4 * cols, 2.8 * rows), sharex=True)
    axes_grid = axes if rows > 1 else [axes]

    for r, row in enumerate(grid):
        for c in range(cols):
            ax = axes_grid[r][c] if rows > 1 else axes_grid[c]
            if c >= len(row):
                ax.axis("off")
                continue
            joint_idx = row[c]
            name = MOTOR_NAMES[joint_idx]
            error = data[f"{name}_q_error"]
            ax.plot(t, error, linewidth=1.2)
            ax.axhline(0.0, color="black", linewidth=0.8, alpha=0.4)
            ax.set_title(f"{joint_idx}: {name}")
            ax.set_ylabel("target - state [rad]")
            ax.grid(True, alpha=0.25)

    bottom_axes = axes_grid[-1] if rows > 1 else axes_grid
    for ax in bottom_axes:
        ax.set_xlabel("time [s]")
    fig.suptitle("Go2 joint tracking error")
    fig.tight_layout()
    fig.savefig(out_path, dpi=160)


def main():
    parser = argparse.ArgumentParser(description="Plot Go2 LowCmd target and LowState feedback CSV.")
    parser.add_argument("csv", help="CSV generated by track_lowcmd_lowstate_go2")
    parser.add_argument("--joints", default="all", help="all, indices like 0,1,2, or names like FR_hip,FR_thigh")
    parser.add_argument("--out-dir", default=None, help="Output directory. Defaults to CSV directory.")
    args = parser.parse_args()

    csv_path = Path(args.csv)
    out_dir = Path(args.out_dir) if args.out_dir else csv_path.parent
    joints = parse_joints(args.joints)
    data = load_csv(csv_path)

    tracking_png = out_dir / "target_state.png"
    error_png = out_dir / "error.png"
    plot_tracking(data, joints, tracking_png)
    plot_error(data, joints, error_png)

    print(f"Saved {tracking_png}")
    print(f"Saved {error_png}")


if __name__ == "__main__":
    main()
