#include "stage_c/body_acceleration.h"
#include <cmath>
#include <iostream>
#include <limits>
#include <stdexcept>
using go2_control::Go2RigidBody;
using go2_control::RigidBodyPlanningKinematics;
using go2_control::RigidBodyState;
using go2_terrain::stage_c::BodyAccelerationTarget;
using go2_terrain::stage_c::BodyReference;
using go2_terrain::stage_c::JointPlannerFailure;
using go2_terrain::stage_c::LiftBodyAcceleration;
using go2_terrain::stage_c::ReconstructBodyReference;
using go2_terrain::stage_c::FiniteBodyAccelerationTarget;
namespace
{
void Check(bool condition, const char *message)
{
    if (!condition)
        throw std::runtime_error(message);
}
RigidBodyState Pose()
{
    RigidBodyState state;
    state.position_world = Eigen::Vector3d(.4, -.1, .43);
    state.quat_world_from_body =
        Eigen::AngleAxisd(.3, Eigen::Vector3d::UnitZ()) *
        Eigen::AngleAxisd(.12, Eigen::Vector3d::UnitY());
    state.q << .05, .7, -1.4, -.05, .65, -1.35,
        .03, .68, -1.37, -.04, .72, -1.42;
    state.dq << .1, -.2, .3, -.1, .1, .2,
        .2, -.3, .1, -.2, .15, -.1;
    state.linear_vel_world = Eigen::Vector3d(.7, .1, -.02);
    state.angular_vel_body = Eigen::Vector3d(.1, -.2, .3);
    return state;
}
BodyReference Reference(const RigidBodyPlanningKinematics &model)
{
    BodyReference reference;
    reference.valid = true;
    reference.foot_reference_valid.fill(true);
    reference.com_world = model.dynamics.com_world;
    reference.com_velocity_world = model.com_velocity_world;
    reference.angular_momentum_world = model.angular_momentum_world;
    for (int leg = 0; leg < 4; ++leg)
    {
        reference.foot_center_world[leg] = model.dynamics.foot_pos_world[leg];
        reference.foot_velocity_world[leg] =
            model.dynamics.foot_jac_world[leg] * model.dynamics.qvel;
    }
    return reference;
}
void SetGeneralizedVelocity(
    Go2RigidBody &robot, RigidBodyState &state,
    const Eigen::Matrix<double, go2_control::kGo2Nv, 1> &velocity)
{
    state.linear_vel_world = velocity.head<3>();
    state.angular_vel_body = velocity.segment<3>(3);
    for (int motor = 0; motor < static_cast<int>(go2::kJointCount); ++motor)
    {
        const int dof = robot.MotorDof(motor);
        Check(dof >= 0 && dof < go2_control::kGo2Nv, "motor dof");
        state.dq[motor] = velocity[dof];
    }
}
// Independent kinematic trajectory oracle. Positions are obtained by the
// model's configuration integrator; velocities at the two samples include the
// prescribed qacc. No map_dot or LiftBodyAcceleration helper is used here.
BodyAccelerationTarget FiniteDifferenceTarget(
    Go2RigidBody &robot, const RigidBodyState &state,
    const Eigen::Matrix<double, go2_control::kGo2Nv, 1> &qvel,
    const Eigen::Matrix<double, go2_control::kGo2Nv, 1> &qacc, double dt)
{
    Check(std::isfinite(dt) && dt > 0.0, "finite difference dt");
    RigidBodyState plus_state, minus_state;
    Check(robot.IntegrateConfiguration(state, qvel, dt, plus_state), "plus trajectory");
    Check(robot.IntegrateConfiguration(state, qvel, -dt, minus_state), "minus trajectory");
    SetGeneralizedVelocity(robot, plus_state, qvel + dt * qacc);
    SetGeneralizedVelocity(robot, minus_state, qvel - dt * qacc);
    RigidBodyPlanningKinematics plus_model, minus_model;
    Check(robot.EvaluatePlanningKinematics(plus_state, plus_model), "plus kinematics");
    Check(robot.EvaluatePlanningKinematics(minus_state, minus_model), "minus kinematics");
    BodyAccelerationTarget target;
    target.com_acceleration_valid = true;
    target.angular_momentum_derivative_valid = true;
    target.foot_acceleration_valid.fill(true);
    target.com_acceleration_world =
        (plus_model.com_velocity_world - minus_model.com_velocity_world) / (2.0 * dt);
    target.angular_momentum_derivative_world =
        (plus_model.angular_momentum_world - minus_model.angular_momentum_world) /
        (2.0 * dt);
    for (int leg = 0; leg < 4; ++leg)
    {
        const auto plus_velocity =
            plus_model.dynamics.foot_jac_world[leg] * plus_model.dynamics.qvel;
        const auto minus_velocity =
            minus_model.dynamics.foot_jac_world[leg] * minus_model.dynamics.qvel;
        target.foot_acceleration_world[leg] =
            (plus_velocity - minus_velocity) / (2.0 * dt);
    }
    Check(FiniteBodyAccelerationTarget(target), "finite acceleration target");
    return target;
}
} // namespace
int main()
{
    try
    {
        Go2RigidBody robot;
        Check(robot.Load(GO2_MODEL_PATH), "model load");
        // Constant translation is a known trajectory with zero qacc. Its
        // target is generated by the independent finite-difference oracle.
        auto translating = Pose();
        translating.linear_vel_world = Eigen::Vector3d(.35, -.12, .04);
        translating.angular_vel_body.setZero();
        translating.dq.setZero();
        RigidBodyPlanningKinematics translating_model;
        Check(robot.EvaluatePlanningKinematics(translating, translating_model),
              "translation model");
        const auto translating_reference = Reference(translating_model);
        const auto translating_reconstruction = ReconstructBodyReference(
            robot, translating, translating_reference);
        Check(translating_reconstruction.kinematics_valid,
              "translation reconstruction");
        const Eigen::Matrix<double, go2_control::kGo2Nv, 1> zero_qacc =
            Eigen::Matrix<double, go2_control::kGo2Nv, 1>::Zero();
        const auto translation_target = FiniteDifferenceTarget(
            robot, translating_reconstruction.state,
            translating_reconstruction.model.dynamics.qvel, zero_qacc, 1.0e-5);
        const auto translation_lift = LiftBodyAcceleration(
            robot, translating_reconstruction, translation_target);
        Check(translation_lift.valid, "constant translation lift");
        Check(translation_lift.failure == JointPlannerFailure::kNone,
              "constant translation failure");
        Check(translation_lift.qacc.norm() < 2.0e-5,
              "constant translation must recover zero qacc");
        // A general known qacc is recovered from a separate trajectory oracle,
        // rather than using the lift's central map derivative to build target.
        RigidBodyState known = Pose();
        RigidBodyPlanningKinematics known_model;
        Check(robot.EvaluatePlanningKinematics(known, known_model),
              "general model");
        const auto known_reference = Reference(known_model);
        const auto reconstruction = ReconstructBodyReference(
            robot, known, known_reference);
        Check(reconstruction.kinematics_valid, "general reconstruction");
        Eigen::Matrix<double, go2_control::kGo2Nv, 1> expected_qacc;
        expected_qacc << .08, -.04, .03, .02, -.06, .05,
            -.07, .05, -.03, .06, -.02, .04, -.05, .03, .07, -.04, .02, -.06;
        const auto target = FiniteDifferenceTarget(
            robot, reconstruction.state, reconstruction.model.dynamics.qvel,
            expected_qacc, 1.0e-5);
        const auto lift = LiftBodyAcceleration(robot, reconstruction, target);
        Check(lift.valid, "general acceleration lift");
        Check(lift.map_rank == go2_control::kGo2Nv, "full acceleration map rank");
        Check(std::isfinite(lift.map_rcond) && lift.map_rcond >= 1.0e-10,
              "acceleration map conditioning");
        Check(lift.residual_inf <= 1.0e-8, "acceleration lift residual");
        Check((lift.qacc - expected_qacc).norm() < 3.0e-3,
              "general qacc recovery");
        auto missing_foot = target;
        missing_foot.foot_acceleration_valid[2] = false;
        const auto invalid_target = LiftBodyAcceleration(
            robot, reconstruction, missing_foot);
        Check(!invalid_target.valid &&
                  invalid_target.failure == JointPlannerFailure::kInvalidInput,
              "missing foot acceleration must fail closed");
        auto bad_options = go2_terrain::stage_c::BodyAccelerationLiftOptions{};
        bad_options.configuration_epsilon_s = std::numeric_limits<double>::quiet_NaN();
        const auto invalid_options = LiftBodyAcceleration(
            robot, reconstruction, target, bad_options);
        Check(!invalid_options.valid &&
                  invalid_options.failure == JointPlannerFailure::kInvalidInput,
              "invalid differentiation option must fail closed");
        std::cout << "body acceleration lift passed: rcond=" << lift.map_rcond
                  << " residual_inf=" << lift.residual_inf
                  << " qacc_error=" << (lift.qacc - expected_qacc).norm() << "\n";
        return 0;
    }
    catch (const std::exception &error)
    {
        std::cerr << error.what() << "\n";
        return 1;
    }
}
