// Current-node coverage/build only; never mj_forward, mj_step or a swept-volume claim.
#include "joint_observed_node_input.h"
#include "../../terrain/stage_c/observed_collision_mujoco.h"
#include <fstream>
#include <iostream>
namespace node=joint_observed_node;
namespace oc=go2_terrain::stage_c::observed_collision;
using namespace go2_terrain::stage_c;
void Number(double x){if(std::isfinite(x))std::cout<<x;else std::cout<<"null";}
void Array(const double* x,int n){std::cout<<'[';for(int i=0;i<n;++i){if(i)std::cout<<',';Number(x[i]);}std::cout<<']';}
void QueryJson(const WorldTerrainSnapshotQueryResult& q){std::cout<<"{\"valid\":"<<(q.ok()?"true":"false")<<",\"source_error\":"<<std::quoted(WorldTerrainSnapshotErrorName(q.error))<<",\"latest_failure\":"<<std::quoted(WorldTerrainQueryFailureName(q.latest_failure))<<",\"selected_sequence\":"<<q.selected_source_sequence<<",\"history_used\":"<<(q.history_used?"true":"false")<<",\"known_cells\":"<<q.diagnostic.patch_known<<",\"total_cells\":"<<q.diagnostic.patch_total<<",\"outside_cells\":"<<q.diagnostic.patch_outside<<'}';}
void SetQv(const mjModel* m,mjData* d,const node::Snapshot& s){
 d->time=s.time;for(int j=0;j<3;++j){d->qpos[j]=s.position[j];d->qvel[j]=s.linear_velocity[j];d->qvel[j+3]=s.angular_velocity[j];}for(int j=0;j<4;++j)d->qpos[j+3]=s.quaternion[j];mju_normalize4(d->qpos+3);
 std::set<int> joints;for(int i=0;i<12;++i){int joint=m->actuator_trnid[2*i];if(m->actuator_trntype[i]!=mjTRN_JOINT||joint<0||joint>=m->njnt||m->jnt_type[joint]!=mjJNT_HINGE||!joints.insert(joint).second)throw std::runtime_error("invalid actuator joint mapping");d->qpos[m->jnt_qposadr[joint]]=s.joints[i];d->qvel[m->jnt_dofadr[joint]]=s.joint_velocities[i];}mj_kinematics(m,d);
}
int main(int argc,char** argv){try{
 if(argc!=6||std::string(argv[5])!="--accept-cell-prism-assumption")throw std::runtime_error("usage: SNAPSHOT ROBOT_XML MAX_AGE_S PRISM_DEPTH_M --accept-cell-prism-assumption");
 std::ifstream input(argv[1]);if(!input)throw std::runtime_error("snapshot unavailable");auto snapshot=node::Parse(input);std::size_t end=0;double age=std::stod(argv[3],&end);if(end!=std::string(argv[3]).size())throw std::runtime_error("invalid max age");double depth=std::stod(argv[4],&end);if(end!=std::string(argv[4]).size())throw std::runtime_error("invalid depth");
 if(!std::isfinite(age)||age<0||!std::isfinite(depth)||depth<=0)throw std::runtime_error("finite nonnegative age and positive depth required");
 oc::Reconstruction reconstruction;reconstruction.accept_cell_prism_assumption=true;reconstruction.max_cell_age_s=age;reconstruction.prism_depth_m=depth;
 char error[2048]{};std::unique_ptr<mjModel,oc::ModelDeleter> robot(mj_loadXML(argv[2],nullptr,error,sizeof(error)));if(!robot)throw std::runtime_error(error);if(!oc::RobotOnly(robot.get()))throw std::runtime_error("robot-only Go2 XML required");
 std::unique_ptr<mjData,decltype(&mj_deleteData)> state(mj_makeData(robot.get()),mj_deleteData);SetQv(robot.get(),state.get(),snapshot);
 std::vector<int> geoms;double xmin=INFINITY,xmax=-INFINITY,ymin=INFINITY,ymax=-INFINITY;
 for(int g=0;g<robot->ngeom;++g){if(!robot->geom_contype[g]&&!robot->geom_conaffinity[g])continue;const double* c=state->geom_xpos+3*g;double radius=robot->geom_rbound[g];if(!std::isfinite(radius)||radius<=0||!std::isfinite(c[0])||!std::isfinite(c[1])||!std::isfinite(c[2]))throw std::runtime_error("invalid collision geom bound");geoms.push_back(g);xmin=std::min(xmin,c[0]-radius);xmax=std::max(xmax,c[0]+radius);ymin=std::min(ymin,c[1]-radius);ymax=std::max(ymax,c[1]+radius);}
 if(geoms.empty())throw std::runtime_error("no collision geometry");oc::Query full;full.world_x=(xmin+xmax)*.5;full.world_y=(ymin+ymax)*.5;for(int g:geoms)full.radius_m=std::max(full.radius_m,std::hypot(state->geom_xpos[3*g]-full.world_x,state->geom_xpos[3*g+1]-full.world_y)+robot->geom_rbound[g]);
 auto built=oc::Build(snapshot.history,full,reconstruction);
 std::cout<<std::setprecision(17)<<"{\"robot_xml\":"<<std::quoted(argv[2])<<",\"source_trust\":\"trusted caller must independently bind canonical robot XML and recursive assets; RobotOnly checks structure, not source authenticity\",\"schema\":\"joint-observed-collision-current-node-v1\",\"scope\":\"full v2 snapshot; current-node q/v kinematics only, not integration state/continuous sweep/physics trajectory\",\"input_tokens\":"<<snapshot.tokens<<",\"snapshot_id\":"<<snapshot.id<<",\"observation_time\":"<<snapshot.time<<",\"epoch\":"<<snapshot.history.metadata.aggregate_epoch<<",\"capture_count\":"<<snapshot.history.captures.size()<<",\"latest_sequence\":"<<snapshot.latest.map_sequence<<",\"max_cell_age_s\":";Number(age);std::cout<<",\"prism_depth_m\":";Number(depth);
 double qnorm=0;for(double q:snapshot.quaternion)qnorm+=q*q;std::cout<<",\"input_quaternion_norm\":"<<std::sqrt(qnorm)<<",\"quaternion_normalized_for_kinematics\":true,\"qpos\":";Array(state->qpos,19);std::cout<<",\"qvel\":";Array(state->qvel,18);
 std::cout<<",\"full_body_query\":{\"world_x\":"<<full.world_x<<",\"world_y\":"<<full.world_y<<",\"radius_m\":"<<full.radius_m<<",\"construction\":\"rotation-independent enclosing radius of every collidable geom center plus rbound; square patch may conservatively include free space between robot geoms\",\"coverage\":";QueryJson(built.coverage);std::cout<<"},\"descriptor_built\":"<<(built.ok()?"true":"false")<<",\"build_failure\":"<<std::quoted(built.failure)<<",\"collidable_geoms\":[";
 for(std::size_t index=0;index<geoms.size();++index){int g=geoms[index];if(index)std::cout<<',';const char* name=mj_id2name(robot.get(),mjOBJ_GEOM,g);const char* body=mj_id2name(robot.get(),mjOBJ_BODY,robot->geom_bodyid[g]);oc::Query q{state->geom_xpos[3*g],state->geom_xpos[3*g+1],robot->geom_rbound[g]};auto coverage=SampleWorldTerrainSnapshot(snapshot.history,q.world_x,q.world_y,q.radius_m,age);std::cout<<"{\"geom_id\":"<<g<<",\"name\":"<<std::quoted(name?name:"")<<",\"body\":"<<std::quoted(body?body:"")<<",\"center_world\":";Array(state->geom_xpos+3*g,3);std::cout<<",\"rbound_m\":"<<q.radius_m<<",\"coverage\":";QueryJson(coverage);std::cout<<",\"captures\":[";
  for(std::size_t j=0;j<snapshot.history.captures.size();++j){if(j)std::cout<<',';const auto& capture=snapshot.history.captures[j];auto evidence=world_terrain_snapshot_detail::InspectModel(snapshot.history,capture.model,q.world_x,q.world_y,q.radius_m,age);std::cout<<"{\"sequence\":"<<capture.model.map_sequence<<",\"source\":"<<std::quoted(go2_terrain::TerrainSourceName(capture.model.source))<<",\"complete\":"<<(evidence.complete?"true":"false")<<",\"failure\":"<<std::quoted(WorldTerrainQueryFailureName(evidence.failure))<<",\"fresh_known_cells\":"<<evidence.fresh_known_cells<<",\"total_cells\":"<<evidence.total_cells<<",\"outside_cells\":"<<evidence.diagnostic.patch_outside<<'}';}std::cout<<"]}";
 }
 std::cout<<"],\"compiled\":";if(!built.ok()){std::cout<<"false,\"robot_consistency\":null}\n";return 0;}
 auto compiled=oc::CompileMujoco(built.descriptor,argv[2]);const auto* m=compiled->model();std::unique_ptr<mjData,decltype(&mj_deleteData)> output(mj_makeData(m),mj_deleteData);SetQv(m,output.get(),snapshot);
 bool topology=m->nq==robot->nq&&m->nv==robot->nv&&m->nu==robot->nu&&m->nbody==robot->nbody;double inertial_delta=0,geom_delta=0,qv_delta=0;bool mapping=true;
 for(int b=1;b<robot->nbody;++b){inertial_delta=std::max(inertial_delta,std::abs(robot->body_mass[b]-m->body_mass[b]));for(int j=0;j<3;++j){inertial_delta=std::max(inertial_delta,std::abs(robot->body_inertia[3*b+j]-m->body_inertia[3*b+j]));inertial_delta=std::max(inertial_delta,std::abs(robot->body_ipos[3*b+j]-m->body_ipos[3*b+j]));}for(int j=0;j<4;++j)inertial_delta=std::max(inertial_delta,std::abs(robot->body_iquat[4*b+j]-m->body_iquat[4*b+j]));topology=topology&&robot->body_geomnum[b]==m->body_geomnum[b];for(int j=0;j<robot->body_geomnum[b];++j){int a=robot->body_geomadr[b]+j,c=m->body_geomadr[b]+j;mapping=mapping&&robot->geom_type[a]==m->geom_type[c]&&robot->geom_contype[a]==m->geom_contype[c]&&robot->geom_conaffinity[a]==m->geom_conaffinity[c];geom_delta=std::max(geom_delta,std::abs(robot->geom_rbound[a]-m->geom_rbound[c]));for(int axis=0;axis<9;++axis)geom_delta=std::max(geom_delta,std::abs(state->geom_xmat[9*a+axis]-output->geom_xmat[9*c+axis]));for(int axis=0;axis<3;++axis){geom_delta=std::max(geom_delta,std::abs(state->geom_xpos[3*a+axis]-output->geom_xpos[3*c+axis]));geom_delta=std::max(geom_delta,std::abs(robot->geom_size[3*a+axis]-m->geom_size[3*c+axis]));}}}
 for(int i=0;i<12;++i)mapping=mapping&&robot->actuator_trnid[2*i]==m->actuator_trnid[2*i]&&robot->actuator_trntype[i]==m->actuator_trntype[i];for(int i=0;i<19;++i)qv_delta=std::max(qv_delta,std::abs(state->qpos[i]-output->qpos[i]));for(int i=0;i<18;++i)qv_delta=std::max(qv_delta,std::abs(state->qvel[i]-output->qvel[i]));
 std::cout<<"true,\"prism_count\":"<<built.descriptor->prisms().size()<<",\"robot_consistency\":{\"topology_equal\":"<<(topology?"true":"false")<<",\"mapping_equal\":"<<(mapping?"true":"false")<<",\"inertial_delta\":"<<inertial_delta<<",\"geom_delta\":"<<geom_delta<<",\"qv_delta\":"<<qv_delta<<"},\"continuous_surface_certified\":false,\"continuous_sweep_certified\":false,\"can_actuate\":false}\n";
 return topology&&mapping&&inertial_delta==0&&geom_delta==0&&qv_delta==0?0:1;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
